### PR TITLE
Add Integrations section to Readme

### PR DESCRIPTION
**Pull request by melonamin**
I have been using these for a while and decided that it might be a good idea to share it with the community.

Utility of Raycast extension is obvious. As for the shortcut, I initially created it to use on my phone, but then quickly realized that the Services menu is a handy way to use it as well.

### CODE REVIEW

**Comment by umputun** [comment]
I have tried the Raycast extension, but it does not work. The main issue is that the URL it returns includes the PIN appended to the correct link with \n in between.

Another minor issue is that the extension allows for the input of a longer PIN. There is an API available for the current settings (`GET /params`) which includes the maximum length of the PIN.

**Comment by umputun** [comment]
I also tried the shortcut, but I was unable to make it work. It did not request a pin at all (perhaps it was expected to autogen it, but I am not sure). The URL it generated included this pin, which was essentially the same as the one mentioned above.

**Comment by umputun** [comment]
for the shortcut i think the bug is here

image

The clipboard section should not include the pin, instead it should only be displayed in notifications.

**Comment by melonamin** [comment]
> the main issue is that the URL it returns includes the PIN appended to the correct link with \n in between.

Hm, this is how it looks for me:


https://github.com/umputun/secrets/assets/222100/6a3677b9-e88b-49a4-9747-008986212a6e


As expected(at least by me!) I get URL and PIN on separate lines, then I can decide if I want to share both or send only a link and pass PIN on a separate channel. Is it different for you?

> Another minor issue is that the extension allows for the input of a longer PIN.

Ha, looks like I messed up a bit...

I am using the `/params` endpoint for auto-generated PINs, but it seems like I misplaced the form validation code. Since I never manually enter the PIN, it slipped through the cracks during my testing. This should be fixed, but will take a while, Raycast's team is quite slow.

> I also tried the shortcut, but I was unable to make it work. It did not request a pin at all (perhaps it was expected to autogen it, but I am not sure).

Yes, it autogenerates, no manual input. 

> The clipboard section should not include the pin, instead it should only be displayed in notifications.

I'm afraid I'm not following...


I think our workflow is a bit different. Let me explain mine:

**Scenario 1**: I need to share an API token with my teammate, let's say it is the OpenAI Key. Here is what I do:
-  Go to the OpenAI platform and generate the key.
-  On Mac: copy the key -> run the Raycast extension with default settings. On iOS: Long press  -> Share -> Run the shortcut (no additional inputs).
-  Go to Slack -> CMD+V -> Send.

I don't want the token to be in the chat history forever, but I'm okay with Safesecret link, since it is a short-lived URL.

**Scenario 2**: I need to share something with a security-conscious person from my customer team. Here is what I do:
-  same
-  same
-  Send the link over email and send the code on a separate channel (either text or call).

So in both cases, it makes sense to copy both the URL and PIN to the clipboard. Having the PIN only in the notification defeats the purpose...

What am I missing?

**Comment by umputun** [comment]
Ok, I understand your intention now. The concept of receiving a URL and a PIN back seems a bit unusual to me, as my initial instinct was to input the result into the browser. However, for Raycast, this is something I would anticipate, since I manually entered the PIN and having it included in the response is quite unexpected. Perhaps it should not add a PIN line if the PIN was manually entered and not automatically generated?

As for the shortcut - it is likely that there is no alternative solution since the PIN is always automatically generated.

**Comment by melonamin** [comment]
> Perhaps it should not add a PIN line if the PIN was manually entered and not automatically generated?

Yes, doable. Or maybe I can offer two actions on the form submition, or two commands - one allows for PIN entry and the other one doesn't. Let me play with it, I see what works better.

> As for the shortcut - it is likely that there is no alternative solution since the PIN is always automatically generated.

Here is an [alternative version](https://www.icloud.com/shortcuts/c0b5d8002d184b4f9c9b4130b7b6bf7b), it lets you choose PIN generation method and produces different result based on it. I wouldn't use it personally, but maybe useful as a second option.

**Pull request merged**
